# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: docker.io/postgres:14-alpine
    container_name: pg_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Secur3P@ss2025!
      POSTGRES_DB: banking_core
    volumes:
      - pg_data:/var/lib/postgresql@14/data
    networks:
      - app_network
    restart: unless-stopped

  backend:
    build: ./New-Account-PoC-Backend
    container_name: backendapp
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app_network
    restart: unless-stopped
  nginx:
    image: docker.io/nginx:1.25-alpine
    container_name: app_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./New-Account-PoC-Frontend-Custemer/dist:/app/dist
    ports:
      - "8081:80"
      - "8443:443"
    depends_on:
      # - frontend
      - backend
    networks:
      - app_network
    restart: unless-stopped

volumes:
  pg_data:

networks:
  app_network:
    driver: bridge
