datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/banking_core?timezone=UTC
  username: postgres
  password: Secur3P@ss2025!
  hikari:
    minimum-idle: 5
    maximum-pool-size: 10
    auto-commit: true
    idle-timeout: 60000
    pool-name: NewAccountHikariCP
    max-lifetime: 600000
    connection-timeout: 30000
    connection-test-query: SELECT 1

springdoc:
  swagger-ui:
    path: /swagger-ui.html

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


